# Generated by Django 2.2 on 2019-12-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogada',
            name='value',
            field=models.CharField(default='?', max_length=10),
        ),
    ]
